'use client';

/**
 * The recurrence card, shared by the action sheet panel and the full
 * action page (they used to carry byte-identical copies — the round-3
 * lesson about duplicates drifting).
 *
 * Review round 4: recurrence confused every tester — "weekly" said
 * nothing about WHAT happens weekly. The card now states the mechanic
 * in words (completing this action creates the next copy), names the
 * exact date the next copy would be due (computed server-side by the
 * same code the completion path runs), links back to the series origin,
 * and says plainly how to stop the series.
 */
import { useTranslations } from 'next-intl';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { formatDate } from '../../lib/format-date';
import { trpc } from '../../lib/trpc/client';
import { useServerErrorToast } from '../../lib/use-server-error';
import { Button } from '../ui/button';
import { Input } from '../ui/input';

export interface RecurrenceCardValue {
  rrule: string;
  endDate: string | null;
}

type Freq = 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'YEARLY';

export function parseFreq(rrule: string | undefined): Freq | null {
  const match = /FREQ=(DAILY|WEEKLY|MONTHLY|YEARLY)/.exec(rrule?.toUpperCase() ?? '');
  return (match?.[1] as Freq | undefined) ?? null;
}

export function parseInterval(rrule: string | undefined): number | null {
  const match = /INTERVAL=(\d+)/.exec(rrule?.toUpperCase() ?? '');
  const value = match?.[1] !== undefined ? parseInt(match[1], 10) : NaN;
  return Number.isFinite(value) && value > 0 ? value : null;
}

export function RecurrenceCard({
  actionId,
  recurrence,
  canEdit,
  locale,
  nextAt,
  parent,
}: {
  actionId: string;
  recurrence: RecurrenceCardValue | null | undefined;
  canEdit: boolean;
  locale: string;
  /** Server-computed: when the next copy would fall due. Null = none. */
  nextAt: Date | null;
  /** The series origin, when this action was generated by recurrence. */
  parent: { id: string; referenceNumber: string | null } | null;
}) {
  const t = useTranslations('actions.detail.recurrence');
  const tCommon = useTranslations('common');
  const onServerError = useServerErrorToast(tCommon('error'));
  const utils = trpc.useUtils();
  const [editing, setEditing] = useState(false);
  const initial = recurrence ?? null;
  const [enabled, setEnabled] = useState(initial !== null);
  const [freq, setFreq] = useState<Freq>(parseFreq(initial?.rrule) ?? 'WEEKLY');
  const [interval, setInterval] = useState<number>(parseInterval(initial?.rrule) ?? 1);
  const [endDate, setEndDate] = useState<string>(
    initial?.endDate !== null && initial?.endDate !== undefined ? initial.endDate.slice(0, 10) : '',
  );

  useEffect(() => {
    setEnabled(initial !== null);
    setFreq(parseFreq(initial?.rrule) ?? 'WEEKLY');
    setInterval(parseInterval(initial?.rrule) ?? 1);
    setEndDate(
      initial?.endDate !== null && initial?.endDate !== undefined
        ? initial.endDate.slice(0, 10)
        : '',
    );
  }, [initial?.rrule, initial?.endDate]);

  const update = trpc.actions.update.useMutation({
    onSuccess: () => {
      toast.success(t('savedToast'));
      void utils.actions.get.invalidate({ actionId });
      setEditing(false);
    },
    onError: onServerError,
  });

  if (!canEdit && initial === null && parent === null) return null;

  const activeFreq = parseFreq(initial?.rrule) ?? 'WEEKLY';
  const activeInterval = parseInterval(initial?.rrule) ?? 1;

  return (
    <section className="space-y-3 border-t p-5 text-sm">
      <div className="flex items-center justify-between">
        <h3 className="font-semibold">{t('title')}</h3>
        {canEdit && !editing ? (
          <Button type="button" variant="ghost" size="sm" onClick={() => setEditing(true)}>
            {tCommon('edit')}
          </Button>
        ) : null}
      </div>

      {parent !== null ? (
        <p className="text-muted-foreground">
          <Link
            href={`/${locale}/actions/${parent.id}`}
            className="font-medium text-primary hover:underline"
          >
            {t('generatedFrom', { reference: parent.referenceNumber ?? '—' })}
          </Link>
        </p>
      ) : null}

      {editing ? (
        <div className="space-y-3">
          <label className="flex items-center gap-2">
            <input
              type="checkbox"
              checked={enabled}
              onChange={(e) => setEnabled(e.target.checked)}
              className="rounded"
            />
            <span>{t('enableLabel')}</span>
          </label>
          <p className="text-xs text-muted-foreground">{t('explainer')}</p>
          {enabled ? (
            <>
              <div className="flex items-center gap-2">
                <span>{t('everyLabel')}</span>
                <Input
                  type="number"
                  min={1}
                  max={99}
                  value={interval}
                  onChange={(e) => setInterval(parseInt(e.target.value, 10) || 1)}
                  className="w-16"
                />
                <select
                  value={freq}
                  onChange={(e) => setFreq(e.target.value as Freq)}
                  className="rounded-md border border-input bg-background px-2 py-1"
                >
                  {(['DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY'] as const).map((f) => (
                    <option key={f} value={f}>
                      {t(`freq.${f.toLowerCase()}` as never)}
                    </option>
                  ))}
                </select>
              </div>
              <div className="flex items-center gap-2">
                <span>{t('endDateLabel')}</span>
                <Input
                  type="date"
                  value={endDate}
                  onChange={(e) => setEndDate(e.target.value)}
                  className="w-auto"
                />
              </div>
            </>
          ) : initial !== null ? (
            <p className="text-xs text-muted-foreground">{t('cancelHint')}</p>
          ) : null}
          <div className="flex justify-end gap-2">
            <Button type="button" variant="ghost" size="sm" onClick={() => setEditing(false)}>
              {tCommon('cancel')}
            </Button>
            <Button
              type="button"
              size="sm"
              disabled={update.isPending}
              onClick={() => {
                if (!enabled) {
                  update.mutate({ actionId, recurrence: null });
                  return;
                }
                const rrule = `FREQ=${freq};INTERVAL=${Math.max(1, Math.min(99, interval))}`;
                update.mutate({
                  actionId,
                  recurrence: {
                    rrule,
                    endDate: endDate === '' ? null : new Date(`${endDate}T23:59:59Z`).toISOString(),
                  },
                });
              }}
            >
              {tCommon('save')}
            </Button>
          </div>
        </div>
      ) : initial !== null ? (
        <div className="space-y-1.5 text-muted-foreground">
          <p className="font-medium text-foreground">
            {t('summary', {
              freq: t(`freq.${activeFreq}` as never),
              unit: t(`unit.${activeFreq}` as never),
              interval: activeInterval,
            })}{' '}
            {initial.endDate !== null
              ? t('endsOn', { date: formatDate(initial.endDate, locale) })
              : t('noEnd')}
          </p>
          <p>{t('explainer')}</p>
          {nextAt !== null ? <p>{t('nextAt', { date: formatDate(nextAt, locale) })}</p> : null}
          {canEdit ? <p className="text-xs">{t('cancelHint')}</p> : null}
        </div>
      ) : (
        <div className="space-y-1.5 text-muted-foreground">
          <p>{t('noRecurrence')}</p>
          {canEdit ? <p className="text-xs">{t('explainer')}</p> : null}
        </div>
      )}
    </section>
  );
}
