/**
 * better-auth tables, with Forma360's tenant extension.
 *
 * These tables back the four core better-auth concepts (user, session,
 * account, verification) plus the two-factor plugin (twoFactor + the
 * `twoFactorEnabled` column on user).
 *
 * The **only** hand-authored addition to what better-auth generates is the
 * `tenant_id` column on `user`. Every human user in Forma360 belongs to
 * exactly one tenant; multi-tenant isolation starts here. Rationale and the
 * regeneration procedure are documented in ADR 0004.
 *
 * Column types match better-auth's expectations precisely (text, boolean,
 * timestamp with timezone). The adapter maps Drizzle TypeScript properties
 * to snake_case columns via our `camelCase` column names below.
 *
 * Forward-only migrations: once a migration referencing these tables is on
 * main, do not edit this file's column shapes. Add a new migration instead.
 */
import { sql } from 'drizzle-orm';
import { boolean, pgTable, text, timestamp } from 'drizzle-orm/pg-core';
import { tenants } from './tenants';

// ─── user ───────────────────────────────────────────────────────────────────

export const user = pgTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified').notNull().default(false),
  image: text('image'),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' })
    .notNull()
    .default(sql`now()`),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' })
    .notNull()
    .default(sql`now()`),

  // ─── Forma360 extensions ──────────────────────────────────────────────────
  /**
   * Tenant this user belongs to. Every user belongs to exactly one tenant.
   * RESTRICT on delete: a tenant cannot be hard-deleted while any user
   * references it — archive the tenant instead (soft-delete via archivedAt)
   * and only hard-delete after a retention period with all users moved.
   */
  tenantId: text('tenant_id')
    .notNull()
    .references(() => tenants.id, { onDelete: 'restrict' }),

  /** Added by the two-factor plugin. Null/false for users without 2FA. */
  twoFactorEnabled: boolean('two_factor_enabled').notNull().default(false),
});

export type User = typeof user.$inferSelect;
export type NewUser = typeof user.$inferInsert;

// ─── session ────────────────────────────────────────────────────────────────

export const session = pgTable('session', {
  id: text('id').primaryKey(),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  token: text('token').notNull().unique(),
  expiresAt: timestamp('expires_at', { withTimezone: true, mode: 'date' }).notNull(),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' })
    .notNull()
    .default(sql`now()`),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' })
    .notNull()
    .default(sql`now()`),
});

export type Session = typeof session.$inferSelect;
export type NewSession = typeof session.$inferInsert;

// ─── account ────────────────────────────────────────────────────────────────

export const account = pgTable('account', {
  id: text('id').primaryKey(),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  accountId: text('account_id').notNull(),
  providerId: text('provider_id').notNull(),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  accessTokenExpiresAt: timestamp('access_token_expires_at', {
    withTimezone: true,
    mode: 'date',
  }),
  refreshTokenExpiresAt: timestamp('refresh_token_expires_at', {
    withTimezone: true,
    mode: 'date',
  }),
  scope: text('scope'),
  idToken: text('id_token'),
  /** Hashed password for email+password accounts. Never the plaintext. */
  password: text('password'),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' })
    .notNull()
    .default(sql`now()`),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' })
    .notNull()
    .default(sql`now()`),
});

export type Account = typeof account.$inferSelect;
export type NewAccount = typeof account.$inferInsert;

// ─── verification ───────────────────────────────────────────────────────────

export const verification = pgTable('verification', {
  id: text('id').primaryKey(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true, mode: 'date' }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' })
    .notNull()
    .default(sql`now()`),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' })
    .notNull()
    .default(sql`now()`),
});

export type Verification = typeof verification.$inferSelect;
export type NewVerification = typeof verification.$inferInsert;

// ─── twoFactor ──────────────────────────────────────────────────────────────

export const twoFactor = pgTable('two_factor', {
  id: text('id').primaryKey(),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  /** TOTP secret (encrypted at rest by better-auth). */
  secret: text('secret').notNull(),
  /** Comma-separated single-use backup codes. */
  backupCodes: text('backup_codes').notNull(),
  /** Whether enrolment has been verified (otherwise this row is pending). */
  verified: boolean('verified').notNull().default(false),
});

export type TwoFactor = typeof twoFactor.$inferSelect;
export type NewTwoFactor = typeof twoFactor.$inferInsert;
